name = "aiocatalogs"
main = "./packages/platforms/cloudflare/index.ts"

compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability]
enabled = true
head_sampling_rate = 1 

[vars]
PORT = "8787"

[[d1_databases]]
binding = "DB"
database_name = "aiocatalogs"
database_id = "55f455b6-3bac-4b05-8292-6de60c26eb9d"
migrations_dir = "./packages/platforms/cloudflare/migrations" 